#!/usr/bin/env python3
"""Execute create-order payloads generated by raw_manual_ingest.py.

Reads JSONL payloads and POSTs each payload to {base_url}/api/orders/.
Auth uses Bearer token via --token or MIGUEL_API_TOKEN.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Execute order create payloads against Miguel API")
    p.add_argument("--input-jsonl", required=True, help="Path to create_orders_api.jsonl")
    p.add_argument("--base-url", required=True, help="API base URL, e.g. https://prod.pureleven.com")
    p.add_argument("--token", default="", help="Bearer token; falls back to MIGUEL_API_TOKEN")
    p.add_argument("--dry-run", action="store_true", help="Print payloads only, do not call API")
    p.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue processing next payload when one fails",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    token = args.token or os.environ.get("MIGUEL_API_TOKEN", "")

    in_path = Path(args.input_jsonl)
    rows = [ln.strip() for ln in in_path.read_text(encoding="utf-8").splitlines() if ln.strip()]
    endpoint = args.base_url.rstrip("/") + "/api/orders/"

    created = 0
    failed = 0

    for idx, line in enumerate(rows, start=1):
        payload = json.loads(line)

        if args.dry_run:
            print(f"[DRY-RUN] #{idx} -> {payload.get('customer_name','-')} | {payload.get('customer_phone','-')}")
            print(json.dumps(payload, ensure_ascii=False))
            continue

        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        req = urllib.request.Request(endpoint, data=body, method="POST")
        req.add_header("Content-Type", "application/json")
        req.add_header("Accept", "application/json")
        if token:
            req.add_header("Authorization", f"Bearer {token}")

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = resp.read().decode("utf-8", errors="replace")
                created += 1
                print(f"[OK] #{idx} status={resp.status} body={data}")
        except urllib.error.HTTPError as e:
            failed += 1
            err = e.read().decode("utf-8", errors="replace")
            print(f"[ERROR] #{idx} status={e.code} body={err}", file=sys.stderr)
            if not args.continue_on_error:
                break
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(f"[ERROR] #{idx} exception={e}", file=sys.stderr)
            if not args.continue_on_error:
                break

    print(json.dumps({"total": len(rows), "created": created, "failed": failed}, indent=2))
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
