"""add_customer_engagement_fields

Revision ID: 036f3cccf5ed
Revises: 33b3caaeaddc
Create Date: 2026-02-20 19:43:58.416825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036f3cccf5ed'
down_revision: Union[str, Sequence[str], None] = '33b3caaeaddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # New engagement tracking columns
    op.add_column('customers', sa.Column('first_order_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('total_orders', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('customers', sa.Column('average_order_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column('abandoned_carts', sa.Integer(), nullable=False, server_default='0'))

    # Add new customer_type enum values (retail, wholesale, distributor)
    op.execute("ALTER TYPE customertype ADD VALUE IF NOT EXISTS 'retail'")
    op.execute("ALTER TYPE customertype ADD VALUE IF NOT EXISTS 'wholesale'")
    op.execute("ALTER TYPE customertype ADD VALUE IF NOT EXISTS 'distributor'")
    # Add meta_ads to sourcetype
    op.execute("ALTER TYPE sourcetype ADD VALUE IF NOT EXISTS 'meta_ads'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'abandoned_carts')
    op.drop_column('customers', 'average_order_value')
    op.drop_column('customers', 'total_orders')
    op.drop_column('customers', 'last_seen_at')
    op.drop_column('customers', 'last_order_date')
    op.drop_column('customers', 'first_order_date')
    # ### end Alembic commands ###
