"""add_meta_ads_module

Revision ID: 0bc432954832
Revises: ab471d322171
Create Date: 2026-02-20 15:39:20.237795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc432954832'
down_revision: Union[str, Sequence[str], None] = 'ab471d322171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('form_id', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('default_assignee_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_assignee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meta_integrations_page_id', 'meta_integrations', ['page_id'], unique=False)
    op.create_index('ix_meta_integrations_tenant_id', 'meta_integrations', ['tenant_id'], unique=False)
    op.create_table('meta_webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=True),
    sa.Column('leadgen_id', sa.String(length=100), nullable=True),
    sa.Column('form_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meta_webhook_logs_leadgen_id', 'meta_webhook_logs', ['leadgen_id'], unique=False)
    op.create_index('ix_meta_webhook_logs_page_id', 'meta_webhook_logs', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meta_webhook_logs_page_id', table_name='meta_webhook_logs')
    op.drop_index('ix_meta_webhook_logs_leadgen_id', table_name='meta_webhook_logs')
    op.drop_table('meta_webhook_logs')
    op.drop_index('ix_meta_integrations_tenant_id', table_name='meta_integrations')
    op.drop_index('ix_meta_integrations_page_id', table_name='meta_integrations')
    op.drop_table('meta_integrations')
    # ### end Alembic commands ###
