"""add_leads_module

Revision ID: 2938e3343f25
Revises: d7e8df45f5f5
Create Date: 2026-02-20 14:09:54.308808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2938e3343f25'
down_revision: Union[str, Sequence[str], None] = 'd7e8df45f5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('manual', 'meta', 'whatsapp', 'google_form', 'website', 'referral', 'cold_call', name='leadsource'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='leadpriority'), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'proposal_sent', 'negotiation', 'won', 'lost', 'on_hold', name='leadpipelinestatus'), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('product_interest', sa.String(length=500), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('converted_customer_id', sa.UUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_by_id', sa.UUID(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['converted_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['converted_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lead_number', name='uq_lead_number_tenant')
    )
    op.create_index('ix_leads_assigned_to', 'leads', ['assigned_to_id'], unique=False)
    op.create_index('ix_leads_converted_customer', 'leads', ['converted_customer_id'], unique=False)
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_next_followup', 'leads', ['next_followup_date'], unique=False)
    op.create_index('ix_leads_phone', 'leads', ['phone'], unique=False)
    op.create_index('ix_leads_priority', 'leads', ['priority'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_leads_tenant_id', 'leads', ['tenant_id'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('call', 'whatsapp', 'sms', 'email', 'visit', 'note', 'status_change', name='leadactivitytype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('old_status', sa.Enum('new', 'contacted', 'qualified', 'proposal_sent', 'negotiation', 'won', 'lost', 'on_hold', name='leadpipelinestatus'), nullable=True),
    sa.Column('new_status', sa.Enum('new', 'contacted', 'qualified', 'proposal_sent', 'negotiation', 'won', 'lost', 'on_hold', name='leadpipelinestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_activities')
    op.drop_index('ix_leads_tenant_id', table_name='leads')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_priority', table_name='leads')
    op.drop_index('ix_leads_phone', table_name='leads')
    op.drop_index('ix_leads_next_followup', table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_index('ix_leads_converted_customer', table_name='leads')
    op.drop_index('ix_leads_assigned_to', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
