"""add_gst_invoice_order_number_v2

Revision ID: 458418b9b413
Revises: f1a2b3c4d5e6
Create Date: 2026-02-21 05:14:57.274685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458418b9b413'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('gst_invoice', sa.Boolean(), nullable=True, server_default='true'))
    op.execute("UPDATE orders SET gst_invoice = true WHERE gst_invoice IS NULL")
    op.alter_column('orders', 'gst_invoice', nullable=False)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('orders', 'gst_invoice')
    # ### end Alembic commands ###
