"""add_gst_variation_fields_to_products

Revision ID: 947175c241e7
Revises: 036f3cccf5ed
Create Date: 2026-02-20 20:12:53.128576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947175c241e7'
down_revision: Union[str, Sequence[str], None] = '036f3cccf5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('tax_inclusive', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('products', sa.Column('variation_name', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('variation_of', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'products', ['variation_of'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'variation_of')
    op.drop_column('products', 'variation_name')
    op.drop_column('products', 'tax_inclusive')
    op.drop_column('products', 'gst_rate')
    op.drop_column('products', 'hsn_code')
    # ### end Alembic commands ###
