"""add_printed_count_to_orders_add_label_whatsapp

Revision ID: ab471d322171
Revises: c9e214abce04
Create Date: 2026-02-20 15:12:11.915679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab471d322171'
down_revision: Union[str, Sequence[str], None] = 'c9e214abce04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('printed_count', sa.Integer(), nullable=False, server_default='0'))
    # remove server_default after backfill so future rows use model default
    op.alter_column('orders', 'printed_count', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'printed_count')
    # ### end Alembic commands ###
