"""add_products_module

Revision ID: c9e214abce04
Revises: e81d578ab548
Create Date: 2026-02-20 14:56:21.601716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e214abce04'
down_revision: Union[str, Sequence[str], None] = 'e81d578ab548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.Enum('kg', 'gram', 'litre', 'ml', 'piece', 'bag', 'box', 'carton', 'bundle', 'pack', name='productunit'), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit_label', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'discontinued', name='productstatus'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_code', name='uq_product_code_tenant'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_product_sku_tenant')
    )
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_index('ix_products_tenant_id', 'products', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
