"""add_customers_module

Revision ID: d7e8df45f5f5
Revises: 3d6a6d828e8c
Create Date: 2026-02-20 13:53:53.609531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e8df45f5f5'
down_revision: Union[str, Sequence[str], None] = '3d6a6d828e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tag_name_tenant')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('unique_customer_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.Enum('home_cook', 'wholesaler', 'retailer', 'mill', name='customertype'), nullable=True),
    sa.Column('payment_mode_preference', sa.Enum('prepaid', 'cod', 'pay_after_delivery', name='paymentmode'), nullable=True),
    sa.Column('source', sa.Enum('manual', 'meta', 'whatsapp', 'google_form', 'website', name='sourcetype'), nullable=True),
    sa.Column('lead_status', sa.Enum('new', 'called', 'interested', 'not_interested', 'lead', 'converted', 'lost', name='leadstatus'), nullable=False),
    sa.Column('interest_status', sa.Enum('hot', 'warm', 'cold', name='intereststatus'), nullable=True),
    sa.Column('assigned_employee_id', sa.UUID(), nullable=True),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'unique_customer_code', name='uq_customer_code_tenant')
    )
    op.create_index('ix_customers_city', 'customers', ['city'], unique=False)
    op.create_index('ix_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_index('ix_customers_interest_status', 'customers', ['interest_status'], unique=False)
    op.create_index('ix_customers_lead_status', 'customers', ['lead_status'], unique=False)
    op.create_index('ix_customers_next_followup', 'customers', ['next_followup_date'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_tenant_id', 'customers', ['tenant_id'], unique=False)
    op.create_table('customer_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.Enum('call', 'whatsapp', 'sms', 'visit', 'note', name='interactiontype'), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('old_status', sa.Enum('new', 'called', 'interested', 'not_interested', 'lead', 'converted', 'lost', name='leadstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('new', 'called', 'interested', 'not_interested', 'lead', 'converted', 'lost', name='leadstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_interested', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_tag_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['customer_tags.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'tag_id', name='uq_customer_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_tag_map')
    op.drop_table('customer_products')
    op.drop_table('customer_interactions')
    op.drop_index('ix_customers_tenant_id', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_next_followup', table_name='customers')
    op.drop_index('ix_customers_lead_status', table_name='customers')
    op.drop_index('ix_customers_interest_status', table_name='customers')
    op.drop_index('ix_customers_created_at', table_name='customers')
    op.drop_index('ix_customers_city', table_name='customers')
    op.drop_table('customers')
    op.drop_table('customer_tags')
    # ### end Alembic commands ###
